### ISSUE TITLE
Issue with "None" route table

### ISSUE THREAD

**Issue by Strandfelt** [StefanIvemo/vwan-playground#15]
**Describe the bug**
First, thanks a lot for this repo. I use it as inspiration.
To compare my setup with this setup, I wanted to deploy this repo as is to an Azure subscription.
However, my deployment fails with the following error on the deployment of weu-lz1-vnet-conn-deploy:
``` 
"message": "The specified propagated route table '/subscriptions/REDACTED/resourceGroups/andtest-vwan-rg/providers/Microsoft.Network/virtualHubs/andtest-vwan-westeurope-vhub/hubRouteTables/None' for connection '/subscriptions/REDACTED/resourceGroups/andtest-vwan-rg/providers/Microsoft.Network/virtualHubs/andtest-vwan-westeurope-vhub/hubVirtualNetworkConnections/peeredTo-weu-lz1-vnet' is invalid 'Please retry another PUT on the propagated route table to populate Nrp Uri Mapping entity for route table.'.",
```

**To Reproduce**
1. Clone repo
2. Select subscription with az account set
3. Run `az deployment sub create -l westeurope --template-file .\playground\main.bicep`

**Additional context**
I changed `contoso` to `andtest` in the config and populated the fields in p2sVpnAADAuth.json. Nothing else.
```
PS C:> az version      
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "alias": "0.5.2",
    "application-insights": "0.1.18",
    "azure-devops": "0.26.0",
    "logic": "0.1.6",
    "virtual-wan": "0.2.15"
  }
}
```
```
PS C:> az bicep version
Bicep CLI version 0.14.46 (ef2ceb1a0e)
```

**Comment by StefanIvemo** [comment]
Thanks for reporting this. Haven't deployed this in a while. Will try to reproduce this.

**Comment by ramuvr** [comment]
I am getting this as well.
<img width="1449" alt="Screenshot 2023-05-24 204433" src="https://github.com/StefanIvemo/vwan-playground/assets/27629864/449d316d-d919-4f2a-a075-422c603e5dde">

**Comment by ramuvr** [comment]
@Strandfelt I updated the APIs:
- Microsoft.Network/virtualHubs@2022-07-01
- Microsoft.Network/virtualHubs/hubRouteTables@2022-07-01
Seems to resolve the issue for me. Could you test and let us know?

**Comment by StefanIvemo** [comment]
I deployed the templates as is today and can't reproduce this.
