### ISSUE TITLE
Add Diagnostics Settings to Virtual Hub - Point to Site

### ISSUE THREAD

**Issue by aavdberg** [StefanIvemo/vwan-playground#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Want to do with code the Diagnostic Settings to the Point to Site in Virtual Hub in the Virtual WAN.

**Additional context**
![image](https://github.com/user-attachments/assets/1f779e5a-c8ee-4a75-8a84-969f111f814f)

**Comment by aavdberg** [comment]
Can do it through the portal but can't find it anywhere in the documentation of ARM or BICEP.

![image](https://github.com/user-attachments/assets/80f92dfd-0006-4aac-ab12-59116275d4be)

**Comment by StefanIvemo** [comment]
Hello,

You should be able to add diagnostics by adding this to your point to site gateway template:

```bicep
resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagnostics'
  scope: pointtositegw //resource identitfier to the point to site gw
  properties: {
    logs: [
      {
        enabled: true
        categoryGroup: 'allLogs'
        retentionPolicy: {
          days: 0
          enabled: false 
        }
      }
    ]
    metrics: [
      {
        enabled: true
        category: 'AllMetrics'
        retentionPolicy: {
          days: 0
          enabled: false 
        }
      }
    ]
    workspaceId: 'resourceId to workspace'
    logAnalyticsDestinationType: 'Dedicated'
  }
}
```
